# Generated by Django 3.0.5 on 2020-05-06 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_sort'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort'], 'verbose_name': '博客分类', 'verbose_name_plural': '博客分类'},
        ),
    ]
