# Generated by Django 3.0.7 on 2020-06-07 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200506_1130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-createTime',), 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
    ]
